import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilePic from '../../public/images/profile/uc.jpg';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icon';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className='flex items-center text-black w-full'>
        <Layout className='pt-3 '>
          <div className='flex items-center justify-between w-full'>
            <div className='w-1/2 h-max rounded-2xl border-2 border-solid border-black bg-green p-2'>
              <Image src={profilePic} alt='img' className='w-full h-auto rounded-2xl' />
            </div>
            <div className='w-1/2 px-5 flex flex-col items-center self-center'>
              <AnimatedText text="Writing Lines That Transform Lives." className='!text-4xl !text-left'/>
              <p className='my-4 text-base font-medium'>
                As a skilled Front-End Web developer, I am dedicated to turning ideas into innovative web applications.
                Explore my latest projects showcasing my abilities in React.js and web development.
              </p>
              <div className='flex items-center self-start mt-2'>
                <Link href='/dummy.pdf' target={"_blank"}
                className='flex items-center bg-black text-white text-lg font-semibold hover:bg-white hover:text-black p-2 px-4 rounded-lg
                border-2 border-solid border-transparent hover:border-black'
                download={true}>
                  Resume <LinkArrow className={"w-6 ml-1"}/>
                </Link> 

                <Link href='mailto:uchechukwu7814@gmail.com' target={"_blank"}
                className='ml-4 text-lg font-medium capitalize text-black underline underline-offset-8'>
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
